spring:
  application:
    name: notification

  # Mail Configuration - MailHog (Testing)
  mail:
    host: localhost
    port: 1025
    username: # No username needed for MailHog
    password: # No password needed for MailHog
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Kafka Configuration (if needed)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # Database Configuration (if needed)
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server Configuration
server:
  port: 8081

# Logging Configuration
logging:
  level:
    com.kurama.notification: DEBUG
    org.springframework.mail: DEBUG

